"""Reusable primitives for the extended email tool suite.

Network operations are deliberately bounded and SMTP targets are resolved and
validated before connecting.  This module never logs or persists credentials.
"""
from __future__ import annotations

import email
import gzip
import io
import ipaddress
import re
import socket
import ssl
import smtplib
import time
from email.message import EmailMessage
import zipfile
import xml.etree.ElementTree as ET
from concurrent.futures import ThreadPoolExecutor

from app.security.ssrf import resolve_host_ips
from app.tools.dns_utils import query_records, query_txt_clean

SMTP_PORTS = frozenset({25, 465, 587, 2525})


def deliver_smtp(*, host: str, port: int, username: str, password: str,
                 sender: str, recipient: str, security: str = "auto",
                 helo_host: str = "analista.to", subject: str = "SMTP Test - Analista.to") -> dict:
    """Send exactly one fixed plaintext test message without retaining secrets.

    The resolved IP is pinned for the TCP connection while the original host is
    retained for TLS SNI/certificate validation. AUTH material is never added to
    the returned transcript.
    """
    if port not in SMTP_PORTS: raise ValueError("SMTP port is not allowed")
    if any(x in recipient for x in ",;\r\n") or any(x in sender for x in "\r\n"):
        raise ValueError("Exactly one sender and one recipient are required")
    ip = str(resolve_host_ips(host)[0]); started = time.monotonic(); events=[]
    def event(message): events.append({"elapsed_ms":round((time.monotonic()-started)*1000),"message":message})
    event(f"Resolved {host} to {ip}")
    context=ssl.create_default_context()
    client = smtplib.SMTP_SSL(ip,port,timeout=8,context=context) if security == "implicit" or port == 465 else smtplib.SMTP(ip,port,timeout=8)
    try:
        client._host=host
        code,banner=client.ehlo(helo_host); event(f"S: {code} {banner.decode('utf-8','replace')}")
        if security in {"auto","starttls"} and client.has_extn("starttls"):
            client.starttls(context=context); event("TLS handshake successful"); client.ehlo(helo_host)
        elif security == "starttls": raise smtplib.SMTPNotSupportedError("STARTTLS not advertised")
        event("C: AUTH [REDACTED]"); client.login(username,password); event("Authentication successful")
        msg=EmailMessage(); msg["From"]=sender; msg["To"]=recipient; msg["Subject"]=subject[:200]
        msg.set_content("This is an SMTP delivery test generated by Analista.to.\n")
        refused=client.send_message(msg,from_addr=sender,to_addrs=[recipient]); event("Message accepted" if not refused else "Recipient refused")
        return {"accepted":not refused,"events":events,"elapsed_ms":round((time.monotonic()-started)*1000),"refused":list(refused)}
    finally:
        try: client.quit()
        except (OSError,smtplib.SMTPException): client.close()


def mx_hosts(domain: str) -> list[tuple[int, str]]:
    found = []
    for value in query_records(domain, "MX"):
        parts = value.split()
        if len(parts) >= 2:
            found.append((int(parts[0]), parts[1].rstrip(".")))
    return sorted(found)


def parse_tags(record: str) -> dict[str, str]:
    return {k.strip().lower(): v.strip() for part in record.split(";") if "=" in part
            for k, v in [part.split("=", 1)]}


def ptr_check(address: str) -> dict:
    ip = ipaddress.ip_address(address)
    host = socket.gethostbyaddr(str(ip))[0].rstrip(".")
    forward = [str(item) for item in resolve_host_ips(host)]
    return {"ip": str(ip), "ptr": host, "forward": forward, "fcrdns": str(ip) in forward}


def smtp_probe(host: str, port: int = 25, timeout: float = 6.0) -> dict:
    if port not in SMTP_PORTS:
        raise ValueError("SMTP port is not allowed")
    ip = str(resolve_host_ips(host)[0])
    context = ssl.create_default_context()
    raw = socket.create_connection((ip, port), timeout=timeout)
    raw.settimeout(timeout)
    sock = context.wrap_socket(raw, server_hostname=host) if port == 465 else raw
    try:
        banner = sock.recv(4096).decode("utf-8", "replace").strip()
        sock.sendall(b"EHLO analista.to\r\n")
        response = sock.recv(16384).decode("utf-8", "replace").strip()
        capabilities = {}
        for line in response.splitlines()[1:]:
            value = re.sub(r"^250[ -]", "", line).strip()
            key, _, arg = value.partition(" ")
            capabilities[key.upper()] = arg or True
        tls = None
        if port != 465 and "STARTTLS" in capabilities:
            sock.sendall(b"STARTTLS\r\n")
            reply = sock.recv(4096).decode("utf-8", "replace")
            if reply.startswith("220"):
                sock = context.wrap_socket(sock, server_hostname=host)
        if isinstance(sock, ssl.SSLSocket) or hasattr(sock, "version"):
            tls = {"version": sock.version(), "cipher": (sock.cipher() or (None,))[0]}
        return {"host": host, "ip": ip, "port": port, "banner": banner,
                "ehlo": response, "capabilities": capabilities, "tls": tls}
    finally:
        try: sock.sendall(b"QUIT\r\n")
        except OSError: pass
        sock.close()


def arc_analysis(raw: str) -> dict:
    msg = email.message_from_string(raw)
    seals = msg.get_all("ARC-Seal", [])
    signatures = msg.get_all("ARC-Message-Signature", [])
    auth = msg.get_all("ARC-Authentication-Results", [])
    instances = sorted({int(x) for value in seals for x in re.findall(r"(?:^|;)\s*i=(\d+)", value)})
    contiguous = instances == list(range(1, len(instances) + 1))
    complete = bool(instances) and len(seals) == len(signatures) == len(auth) == len(instances)
    return {"instances": instances, "seal_count": len(seals), "signature_count": len(signatures),
            "auth_results_count": len(auth), "status": "pass" if complete and contiguous else "fail",
            "issues": [] if complete and contiguous else ["ARC chain is incomplete or inconsistent."]}


def authentication_analysis(raw: str) -> dict:
    msg = email.message_from_string(raw)
    values = msg.get_all("Authentication-Results", [])
    def states(name): return re.findall(rf"\b{name}=(\w+)", " ".join(values), re.I)
    results = {name: [x.lower() for x in states(name)] for name in ("spf", "dkim", "dmarc")}
    summary = {k: ("conflict" if len(set(v)) > 1 else (v[0] if v else "unknown")) for k, v in results.items()}
    summary["arc"] = arc_analysis(raw)["status"] if msg.get_all("ARC-Seal") else "unknown"
    return {"authentication": summary, "raw_results": results, "from": msg.get("From"),
            "return_path": msg.get("Return-Path"), "conflicts": [k for k,v in summary.items() if v == "conflict"]}


def parse_dmarc_report(payload: bytes, filename: str = "report.xml") -> dict:
    if len(payload) > 10 * 1024 * 1024: raise ValueError("Report exceeds the 10 MB limit")
    lower = filename.lower()
    if lower.endswith(".gz"): payload = gzip.decompress(payload)
    elif lower.endswith(".zip"):
        with zipfile.ZipFile(io.BytesIO(payload)) as archive:
            safe = [x for x in archive.infolist() if not x.is_dir() and x.filename.lower().endswith(".xml")]
            if not safe or any(x.file_size > 10 * 1024 * 1024 for x in safe): raise ValueError("Invalid report archive")
            payload = archive.read(safe[0])
    root = ET.fromstring(payload)
    rows=[]
    for record in root.findall(".//record"):
        get=lambda path, default="": record.findtext(path, default)
        rows.append({"ip":get("row/source_ip"), "count":int(get("row/count","0")),
                     "disposition":get("row/policy_evaluated/disposition"),
                     "dkim":get("row/policy_evaluated/dkim"), "spf":get("row/policy_evaluated/spf")})
    return {"total": sum(x["count"] for x in rows), "rows": rows,
            "spf_pass": sum(x["count"] for x in rows if x["spf"] == "pass"),
            "dkim_pass": sum(x["count"] for x in rows if x["dkim"] == "pass")}


def parallel(checks: dict[str, callable]) -> dict:
    with ThreadPoolExecutor(max_workers=min(8, len(checks))) as pool:
        futures = {name: pool.submit(fn) for name, fn in checks.items()}
        result = {}
        for name, future in futures.items():
            try: result[name] = future.result(timeout=12)
            except Exception as exc: result[name] = {"status": "error", "message": str(exc)}
        return result
