"""add monitoring models

Revision ID: 3ab23f34b90a
Revises: 53f5e23c5207
Create Date: 2026-08-01 00:13:01.723848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab23f34b90a'
down_revision = '53f5e23c5207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('check_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_domains_domain'), ['domain'], unique=False)

    op.create_table('monitoring_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitored_domain_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitored_domain_id'], ['monitored_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_alerts_monitored_domain_id'), ['monitored_domain_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_alerts_monitored_domain_id'))

    op.drop_table('monitoring_alerts')
    with op.batch_alter_table('monitored_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_domains_domain'))

    op.drop_table('monitored_domains')
    # ### end Alembic commands ###
