"""modelo inicial

Revision ID: 5ff5f88f1a67
Revises: 
Create Date: 2026-07-27 01:54:09.570642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ff5f88f1a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_categories_slug'), ['slug'], unique=True)

    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('handler', sa.String(length=160), nullable=False),
    sa.Column('input_type', sa.Enum('domain', 'url', 'ip', 'email', 'host_port', 'text', name='inputtype', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_publicly_indexable', sa.Boolean(), nullable=False),
    sa.Column('requires_captcha', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('result_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tool_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handler')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_slug'), ['slug'], unique=True)

    op.create_table('abuse_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('rate_limit_exceeded', 'captcha_failed', 'ssrf_blocked', 'invalid_input', 'suspicious_pattern', 'blocked_origin', name='abuseeventtype', native_enum=False, length=30), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abuse_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abuse_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_abuse_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_abuse_events_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_abuse_events_tool_id'), ['tool_id'], unique=False)

    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('original_input', sa.Text(), nullable=False),
    sa.Column('normalized_input', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('input_type', sa.Enum('domain', 'url', 'ip', 'email', 'host_port', 'text', name='inputtype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('queued', 'validating', 'captcha_check', 'processing', 'querying', 'analyzing', 'generating_report', 'generating_page', 'completed', 'failed', 'expired', 'cancelled', name='searchstatus', native_enum=False, length=20), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', name='searchvisibility', native_enum=False, length=10), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_normalized_input'), ['normalized_input'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_searches_status'), ['status'], unique=False)
        batch_op.create_index('ix_searches_tool_dedupe_status', ['tool_id', 'dedupe_key', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_tool_id'), ['tool_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_visibility'), ['visibility'], unique=False)

    op.create_table('generated_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('canonical_url', sa.String(length=500), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=False),
    sa.Column('seo_description', sa.Text(), nullable=False),
    sa.Column('index_status', sa.Enum('pending', 'index', 'noindex', 'removed', name='indexstatus', native_enum=False, length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_pages_index_status'), ['index_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_pages_search_id'), ['search_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_generated_pages_slug'), ['slug'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'validating', 'captcha_check', 'processing', 'querying', 'analyzing', 'generating_report', 'generating_page', 'completed', 'failed', 'expired', 'cancelled', name='searchstatus', native_enum=False, length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_events_search_id'), ['search_id'], unique=False)

    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('normalized_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_results_result_hash'), ['result_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_results_search_id'), ['search_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_results_search_id'))
        batch_op.drop_index(batch_op.f('ix_search_results_result_hash'))

    op.drop_table('search_results')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_search_id'))
        batch_op.drop_index(batch_op.f('ix_job_events_created_at'))

    op.drop_table('job_events')
    with op.batch_alter_table('generated_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_generated_pages_search_id'))
        batch_op.drop_index(batch_op.f('ix_generated_pages_index_status'))

    op.drop_table('generated_pages')
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searches_visibility'))
        batch_op.drop_index(batch_op.f('ix_searches_tool_id'))
        batch_op.drop_index('ix_searches_tool_dedupe_status')
        batch_op.drop_index(batch_op.f('ix_searches_status'))
        batch_op.drop_index(batch_op.f('ix_searches_public_id'))
        batch_op.drop_index(batch_op.f('ix_searches_normalized_input'))
        batch_op.drop_index(batch_op.f('ix_searches_input_hash'))
        batch_op.drop_index(batch_op.f('ix_searches_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_searches_created_at'))

    op.drop_table('searches')
    with op.batch_alter_table('abuse_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abuse_events_tool_id'))
        batch_op.drop_index(batch_op.f('ix_abuse_events_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_abuse_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_abuse_events_created_at'))

    op.drop_table('abuse_events')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_slug'))
        batch_op.drop_index(batch_op.f('ix_tools_category_id'))

    op.drop_table('tools')
    with op.batch_alter_table('tool_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_categories_slug'))

    op.drop_table('tool_categories')
    # ### end Alembic commands ###
